### ISSUE TITLE
Prod minor bugs/changes TODO list

### ISSUE THREAD

**Issue by tomlynchRNA** [rnadigital/agentcloud#292]
small stuff:
- [x] open customer portal in new tab
- [x] make TrialNag also show when on free plan and prompt to "upgrade" instead of link to billing
- [x] Hide account page for now, nothing on it
- [x] change redirect on oauth login to go to apps screen
- [x] dont show draft datasources on frontend (until we have a way to complete them and get out of draft stage)
- [x] change "type" label in model form to "vendor"
- [x] make websocket more reliable for notifications
- [x] dont show agents dropdown when no agents in chat app form
- [x] dont show human input tool usage
- [x] fix empty message(s) that just show "x tokens just now" 
- [x] Show app name at top of chat
- [x] Add restart/new session button at top of chat
- [x] make conversation starters show after the initial greeting in chat apps (adjust message count)
- [x] add gpt-4o-mini and remove some outdated oai model snapshots
- [x] Change buttons on subscription cards to be always clickable on another plan
- [x] When switching plan to free, dont prompt for payment details
- [x] dont change tool status to READY after edit if a deployment wasn't run
- [x] add discord link in footer
 
to become separate issues (bigger changes required/affects multiple apps/requires data model changes):
- [x] expose top-k in RAG tool settings, propagate to agent backend and send in retrieval options. Plus any other options
- [ ] #304
- [ ] #305
- [ ] #306
- [ ] #307
- stream schema bugs
  - [x] fix time weighted retriever time weight field being empty
  - [ ] fix stream keys and descriptions not being present when expanding unless you hit "edit streams"
  - [ ] make description fields in "edit streams" to be prepopulated with existing values
  - [ ] #308

**Comment by tomlynchRNA** [comment]
ref 00ce94fa6774881581e1ab57c35f4045da79069a
